#!/usr/bin/env python3

import rospy
from sensor_msgs.msg import JointState

from markers import *
from functions import *

global qpos
qpos = [0,0,0,0,0,0,0]

def callback(msg):
    global qpos
    qpos = msg.position

if __name__ == '__main__':
    
    rospy.init_node("testFKineSliders")
    rospy.Subscriber("/joint_states",JointState,callback)
    bmarker = BallMarker(color['GREEN'])
    # Loop rate (in Hz)
    rate = rospy.Rate(30)
    # Continuous execution loop
    while not rospy.is_shutdown():
        T = fkine_mmgp8(qpos)
        # print(np.round(T, 3))
        bmarker.position(T)
        bmarker.publish()
        # Wait for the next iteration
        rate.sleep()
