#!/usr/bin/env python3

import rospy
from sensor_msgs.msg import JointState
from markers import *
from functions import *

if __name__ == '__main__':

    rospy.init_node("testInvKine")
    pub = rospy.Publisher('joint_states', JointState, queue_size=1)

    bmarker      = BallMarker(color['RED'])
    bmarker_des  = BallMarker(color['GREEN'])

    # Joint names
    jnames = ['joint_0_s','joint_1_s','joint_2_l','joint_3_u','joint_4_r','joint_5_b','joint_6_t']

    # Desired position
    xd = np.array([0.2, 0.3, 1])
    # Initial configuration
    q0 = np.array([-0.5, 2, 1.3, -1.2, -2, 2,5])
    # Inverse kinematics
    q = ikine_mmgp8(xd, q0)

    # Resulting position (end effector with respect to the base link)
    T = fkine_mmgp8(q)
    print('Obtained value:\n', np.round(T,3))
    x=T[0:3,3]
    # Red marker shows the achieved position
    bmarker.xyz(x)
    # Green marker shows the desired position
    bmarker_des.xyz(xd)

    # Objeto (mensaje) de tipo JointState
    jstate = JointState()
    # Asignar valores al mensaje
    jstate.header.stamp = rospy.Time.now()
    jstate.name = jnames
    # Add the head joint value (with value 0) to the joints
    jstate.position = q

    # Loop rate (in Hz)
    rate = rospy.Rate(100)
    
    # Continuous execution loop
    while not rospy.is_shutdown():
        # Current time (needed for ROS)
        jstate.header.stamp = rospy.Time.now()
        # Publish the message
        pub.publish(jstate)
        bmarker.publish()
        bmarker_des.publish()
        # Wait for the next iteration
        rate.sleep()
